/**
 * Auto-generated Zod schemas for Devil components
 * DO NOT EDIT - Generated by scripts/component-registry/index.ts
 *
 * These schemas enable runtime validation of AI-generated UI trees.
 */

import { z } from "zod";

// SafeParseReturnType was removed in Zod v4, but we still want stable typing.
export type SafeParseResult<T> =
  | { success: true; data: T; error?: never }
  | { success: false; error: z.ZodError<any>; data?: never };

// =============================================================================
// Dynamic Value Schema (for data binding)
// =============================================================================

/**
 * A value that can either be a literal or a reference to the data model.
 * Example: "Hello" or { path: "/user/name" }
 */
export const DynamicValueSchema = z.union([
  z.string(),
  z.number(),
  z.boolean(),
  z.null(),
  z.object({ path: z.string() }),
]);

export type DynamicValue<T = unknown> = T | { path: string };

// =============================================================================
// Visibility Condition Schemas
// =============================================================================

/**
 * Visibility conditions for conditional rendering.
 * Components can be shown/hidden based on data, auth, or logic expressions.
 */

// Forward declaration for recursive types
// Note: Numeric comparisons use DynamicValue (not DynamicValue<number>) for Zod compatibility
export type LogicExpression =
  | { and: LogicExpression[] }
  | { or: LogicExpression[] }
  | { not: LogicExpression }
  | { path: string }
  | { eq: [DynamicValue, DynamicValue] }
  | { neq: [DynamicValue, DynamicValue] }
  | { gt: [DynamicValue, DynamicValue] }
  | { gte: [DynamicValue, DynamicValue] }
  | { lt: [DynamicValue, DynamicValue] }
  | { lte: [DynamicValue, DynamicValue] };

// Lazy schema for recursive logic expressions
const LogicExpressionSchema: z.ZodType<LogicExpression> = z.lazy(() =>
  z.union([
    z.object({ and: z.array(LogicExpressionSchema) }),
    z.object({ or: z.array(LogicExpressionSchema) }),
    z.object({ not: LogicExpressionSchema }),
    z.object({ path: z.string() }),
    z.object({ eq: z.tuple([DynamicValueSchema, DynamicValueSchema]) }),
    z.object({ neq: z.tuple([DynamicValueSchema, DynamicValueSchema]) }),
    z.object({ gt: z.tuple([DynamicValueSchema, DynamicValueSchema]) }),
    z.object({ gte: z.tuple([DynamicValueSchema, DynamicValueSchema]) }),
    z.object({ lt: z.tuple([DynamicValueSchema, DynamicValueSchema]) }),
    z.object({ lte: z.tuple([DynamicValueSchema, DynamicValueSchema]) }),
  ])
);

export const VisibilityConditionSchema = z.union([
  z.boolean(),
  z.object({ path: z.string() }),
  z.object({ auth: z.enum(["signedIn", "signedOut"]) }),
  LogicExpressionSchema,
]);

export type VisibilityCondition = z.infer<typeof VisibilityConditionSchema>;

// =============================================================================
// Action Schemas
// =============================================================================

/**
 * Action confirmation dialog configuration
 */
export const ActionConfirmSchema = z.object({
  title: z.string(),
  message: z.string(),
  variant: z.enum(["default", "danger"]).optional(),
  confirmLabel: z.string().optional(),
  cancelLabel: z.string().optional(),
});

/**
 * Action definition that AI can declare
 */
export const ActionSchema = z.object({
  name: z.string(),
  params: z.record(z.string(), DynamicValueSchema).optional(),
  confirm: ActionConfirmSchema.optional(),
  onSuccess: z.object({ set: z.record(z.string(), DynamicValueSchema) }).optional(),
  onError: z.object({ set: z.record(z.string(), DynamicValueSchema) }).optional(),
});

export type Action = z.infer<typeof ActionSchema>;

// =============================================================================
// Component Props Schemas
// =============================================================================

export const AutocompletePropsSchema = z.object({
  items: z.array(z.unknown()), // Array of items to display in the dropdown
  value: z.array(z.unknown()).optional(), // The controlled input value
  open: z.boolean().optional(), // Whether the popup is open (controlled)
  children: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // Autocomplete content (input group, popup content)
  className: z.string().optional(), // Additional CSS classes
  label: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // Label content (enables Field wrapper)
  required: z.boolean().optional(), // Whether the field is required
  labelTooltip: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // Tooltip content to display next to the label
  description: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // Helper text displayed below the field
  error: z.unknown().optional(), // Error message or validation error object
});

export const BadgePropsSchema = z.object({
  variant: z.enum(["primary", "secondary", "error", "warning", "success", "destructive", "info", "beta", "outline", "red", "green", "neutral", "orange", "purple", "teal", "teal-subtle", "blue"]).optional(), // Color variant of the badge. Recommended semantic variants: - `"primary"` — Primary badge - `"secondary"` — Secondary badge - `"error"` — Error badge - `"warning"` — Warning badge - `"success"` — Success badge - `"info"` — Info badge Additional token variants: - `"red"`, `"orange"`, `"green"`, `"teal"`, `"blue"`, `"purple"`, `"neutral"` - `"teal-subtle"`, `"neutral-subtle"` - `"inverted"` - `"outline"` — Bordered badge with the base background - `"beta"` — Dashed-border badge for beta/experimental features
  className: z.string().optional(), // Additional CSS classes merged via `cn()`.
  children: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // Content rendered inside the badge.
  appearance: z.enum(["filled", "dot"]).optional(), // Visual appearance of the badge. - `"filled"` — Filled background using the variant color (default) - `"dot"` — Outlined badge with a colored circle dot. Only `success`,   `warning`, `error`, and `neutral` variants show a dot. Dot badges do not   accept icons.
  icon: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // Icon from `@phosphor-icons/react` or a React element. Rendered before children.
});

export const BannerPropsSchema = z.object({
  className: z.string().optional(), // Additional CSS classes merged via `cn()`.
  id: z.string().optional(),
  lang: z.string().optional(),
  icon: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // Icon element rendered before the banner content (e.g. from `@phosphor-icons/react`).
  title: z.string().optional(), // Primary heading text for the banner. Use for i18n string injection.
  description: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // Secondary description text displayed below the title. Use for i18n string injection.
  action: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // Action slot for a CTA button or link. Compact banners render a Devil `Link` inline with the description; CTAs render at the trailing end. Use `Banner.Action` for accent-aware CTAs that self-style to the banner variant; other nodes are rendered as-is. Multiple actions can be passed in a Fragment. Only used in structured mode (with `title` or `description`).
  text: z.string().optional(),
  children: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(),
  variant: z.enum(["default", "alert", "error", "secondary"]).optional(), // Visual style of the banner. - `"default"` — Informational blue banner for general messages - `"alert"` — Warning yellow banner for cautionary messages - `"error"` — Error red banner for critical issues - `"secondary"` — Neutral banner for secondary messages
  size: z.enum(["base", "sm"]).optional(), // Size of the banner. A `"sm"` banner uses tighter spacing and `text-sm`, renders a Devil `Link` action inline with the description, and sets its `Banner.Action` children to the `"xs"` size — suited to dialogs and other tight spaces.
});

export const BreadcrumbsPropsSchema = z.object({
  size: z.enum(["sm", "base"]).optional(), // Size of the breadcrumbs. - `"sm"` — Compact breadcrumbs for dense UIs - `"base"` — Default breadcrumbs size
  children: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(),
  className: z.string().optional(), // Additional CSS classes merged via `cn()`.
});

export const BubbleMapPropsSchema = z.object({
  echarts: z.unknown(), // The ECharts core instance imported by the consumer (passed in for tree-shaking). Requires `MapChart`, `ScatterChart`, `TooltipComponent`, and a renderer registered via `echarts.use([...])`.
  geoJson: z.unknown(), // GeoJSON `FeatureCollection` for the land base.
  mapName: z.string().optional(), // Optional stable ECharts map registry name. Set this when the same GeoJSON is parsed into new object instances across mounts and should reuse one global ECharts registration.
  data: z.array(z.unknown()), // Raw data rows. Coordinates/value/name are read via the accessors below.
  lng: z.unknown(), // Longitude accessor (key of `T` or `(row) => number`).
  lat: z.unknown(), // Latitude accessor (key of `T` or `(row) => number`).
  value: z.unknown(), // Value accessor — drives bubble size.
  name: z.unknown().optional(), // Optional name accessor — used by the default tooltip.
  minRadius: z.number().optional(), // Smallest bubble radius in px. Default: `6`.
  maxRadius: z.number().optional(), // Largest bubble radius in px. Default: `26`.
  bubbleSize: z.unknown().optional(), // Explicit bubble radius `(value) => px`. Overrides the default `minRadius`/`maxRadius` scaling.
  bubbleColor: z.unknown().optional(), // Bubble fill colour — constant or `(row) => color`. Defaults to the chart blue.
  bubbleBorderColor: z.unknown().optional(), // Bubble border colour — constant or `(row) => color`. Default: `transparent`.
  bubbleBorderWidth: z.unknown().optional(), // Bubble border width — constant or `(row) => px`. Default: `0`.
  center: z.unknown().optional(), // Map center as `[longitude, latitude]`. Defaults to auto-fit.
  zoom: z.number().optional(), // Zoom level — multiplies the auto-fit scale. Default: `1.25`.
  roam: z.boolean().optional(), // Enable drag-to-pan and scroll-to-zoom. Default: `false`.
  projection: z.unknown().optional(), // Geographic projection. Defaults to a latitude-clamped Mercator (flat 2D web-map look). Pass another d3-geo projection to override, or `null` for ECharts' raw equirectangular plotting. Use a stable reference (module-level or memoised): a new object each render rebuilds the view and resets a roamed/zoomed map.
  showTooltip: z.boolean().optional(), // Show the tooltip. Default: `true`.
  valueFormat: z.unknown().optional(), // Format the value for the default tooltip. Default: `toLocaleString()`.
  tooltipFormatter: z.unknown().optional(), // Override the tooltip content for a row. Returns an HTML string rendered by ECharts' own tooltip. USE WITH CAUTION: the return value is injected as HTML. Escape any user-provided strings to avoid XSS.
  aspectRatio: z.unknown().optional(), // Container aspect ratio as `width / height` (e.g. `1.7` or `"16 / 9"`). The height derives from the rendered width so the map fills the frame with no letterboxing. Defaults to the projected aspect of the displayed window, so the land fits edge-to-edge. Pass `height` to fix a pixel height instead.
  height: z.number().optional(), // Fixed chart height in pixels. Overrides `aspectRatio` when set. Leave unset to size by aspect ratio (the default) so the map fills the container.
  className: z.string().optional(),
  isDarkMode: z.boolean().optional(),
});

export const ButtonPropsSchema = z.object({
  shape: z.enum(["base", "square", "circle"]).optional(),
  size: z.enum(["xs", "sm", "base", "lg"]).optional(),
  variant: z.enum(["primary", "secondary", "ghost", "destructive", "secondary-destructive", "outline"]).optional(),
  children: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(),
  className: z.string().optional(),
  icon: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // Icon from `@phosphor-icons/react` or a React element. Rendered before children.
  loading: z.boolean().optional(), // Shows a loading spinner and disables interaction.
  title: z.string().optional(),
  id: z.string().optional(),
  lang: z.string().optional(),
  disabled: z.boolean().optional(),
  name: z.string().optional(),
  type: z.enum(["submit", "reset", "button"]).optional(),
  value: z.unknown().optional(),
});

export const ButtonGroupPropsSchema = z.object({
  className: z.string().optional(), // Additional CSS classes merged via `cn()`. Use devil semantic tokens only.
  id: z.string().optional(),
  lang: z.string().optional(),
  title: z.string().optional(),
  children: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // The tightly-coupled controls to join. Typically two `Button`s: a primary action and a dropdown trigger (a "split button").
});

export const ChartPropsSchema = z.object({
  echarts: z.unknown(), // The ECharts core instance imported by the consumer. Passed in rather than imported directly so the consumer controls which ECharts modules are bundled (tree-shaking).
  options: z.unknown(), // ECharts option object — passed through to `chart.setOption()`
  optionUpdateBehavior: z.unknown().optional(), // Additional options passed as the second argument to `chart.setOption()`. Defaults to `{ notMerge: false, lazyUpdate: true }`.
  className: z.string().optional(), // Additional CSS classes applied to the chart container `<div>`
  isDarkMode: z.boolean().optional(), // When `true`, initialises ECharts with its built-in dark theme. Changing this value after mount destroys and re-creates the chart instance.
  height: z.number().optional(), // Height of the chart container in pixels. Defaults to `350`.
  aspectRatio: z.unknown().optional(), // Container aspect ratio as `width / height` (e.g. `1.7` or `"16 / 9"`). When set, the height derives from the rendered width via CSS `aspect-ratio` and the `height` prop is ignored — useful for maps so the canvas matches the map's shape and fills the frame with no letterboxing.
});

export const CheckboxPropsSchema = z.object({
  variant: z.enum(["default", "error"]).optional(), // Visual variant: "default" or "error" for validation failures (visual only, no error text)
  label: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // Label content for the checkbox (enables built-in Field wrapper) - can be a string or any React node
  labelTooltip: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // Tooltip content to display next to the label via an info icon
  controlFirst: z.boolean().optional(), // When true (default), checkbox appears before label. When false, label appears before checkbox.
  checked: z.boolean().optional(), // Whether the checkbox is checked (controlled)
  indeterminate: z.boolean().optional(), // Whether the checkbox is in indeterminate state
  disabled: z.boolean().optional(), // Whether the checkbox is disabled
  name: z.string().optional(), // Name for form submission
  required: z.boolean().optional(), // Whether the field is required
  className: z.string().optional(), // Additional class name
});

export const ChoroplethMapPropsSchema = z.object({
  echarts: z.unknown(), // The ECharts core instance imported by the consumer (passed in for tree-shaking). Requires `MapChart`, `VisualMapComponent`, `TooltipComponent`, and a renderer registered via `echarts.use([...])`.
  geoJson: z.unknown(), // GeoJSON `FeatureCollection` whose regions are shaded by value.
  mapName: z.string().optional(), // Optional stable ECharts map registry name. Set this when the same GeoJSON is parsed into new object instances across mounts and should reuse one global ECharts registration.
  data: z.array(z.unknown()), // Raw data rows. The region key and value are read via the accessors below.
  name: z.unknown(), // Region-key accessor (key of `T` or `(row) => string`). Each row is joined to a GeoJSON feature whose `nameProperty` equals this value.
  value: z.unknown(), // Value accessor — drives the region's fill colour.
  nameProperty: z.string().optional(), // GeoJSON feature property to join on. Default: `"name"`. Real-world data is often more reliably matched on an ISO-code property (e.g. `"iso_a2"`).
  colorRange: z.array(z.string()).optional(), // Sequential colour ramp (low → high). Defaults to the Devil choropleth blues, tuned to stay distinct from the no-data fill. Distributed across the continuous gradient.
  noDataColor: z.string().optional(), // Fill for regions with no matching data row. Defaults to the neutral land grey.
  showLegend: z.boolean().optional(), // Show the visualMap colour legend. Default: `false`.
  showTooltip: z.boolean().optional(), // Show the tooltip. Default: `true`.
  valueFormat: z.unknown().optional(), // Format the value for the default tooltip. Default: `toLocaleString()`.
  tooltipFormatter: z.unknown().optional(), // Override the tooltip content for a row. Returns an HTML string rendered by ECharts' own tooltip. USE WITH CAUTION: the return value is injected as HTML. Escape any user-provided strings to avoid XSS.
  center: z.unknown().optional(), // Map center as `[longitude, latitude]`. Defaults to auto-fit.
  zoom: z.number().optional(), // Zoom level — multiplies the auto-fit scale. Default: `1.25`.
  roam: z.boolean().optional(), // Enable drag-to-pan and scroll-to-zoom. Default: `false`.
  projection: z.unknown().optional(), // Geographic projection. Defaults to a latitude-clamped Mercator (flat 2D web-map look). Pass another d3-geo projection to override, or `null` for ECharts' raw equirectangular plotting. Use a stable reference (module-level or memoised): a new object each render rebuilds the view and resets a roamed/zoomed map.
  aspectRatio: z.unknown().optional(), // Container aspect ratio as `width / height` (e.g. `1.7` or `"16 / 9"`). The height derives from the rendered width so the map fills the frame with no letterboxing. Defaults to the projected aspect of the displayed window, so the regions fit edge-to-edge. Pass `height` to fix a pixel height instead.
  height: z.number().optional(), // Fixed chart height in pixels. Overrides `aspectRatio` when set. Leave unset to size by aspect ratio (the default) so the map fills the container.
  className: z.string().optional(),
  isDarkMode: z.boolean().optional(),
});

export const ClipboardTextPropsSchema = z.object({
  size: z.enum(["sm", "base", "lg"]).optional(), // Size of the clipboard text field. - `"sm"` — Small clipboard text for compact UIs - `"base"` — Default clipboard text size - `"lg"` — Large clipboard text for prominent display
  text: z.string(), // The text to display and copy to clipboard.
  textToCopy: z.string().optional(), // If provided, this text will be copied to clipboard instead of the `text` prop.
  className: z.string().optional(), // Additional CSS classes merged via `cn()`.
  tooltip: z.unknown().optional(), // Tooltip config. Shows tooltip on hover, anchored toast on click.
  labels: z.unknown().optional(), // Accessible labels for i18n.
});

export const CloudflareLogoPropsSchema = z.object({
  children: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(),
  className: z.string().optional(),
  height: z.unknown().optional(),
  id: z.string().optional(),
  lang: z.string().optional(),
  media: z.string().optional(),
  method: z.string().optional(),
  name: z.string().optional(),
  target: z.string().optional(),
  type: z.string().optional(),
  width: z.unknown().optional(),
  accentHeight: z.unknown().optional(),
  accumulate: z.enum(["none", "sum"]).optional(),
  additive: z.enum(["replace", "sum"]).optional(),
  alignmentBaseline: z.enum(["auto", "baseline", "before-edge", "text-before-edge", "middle", "central", "after-edge", "text-after-edge", "ideographic", "alphabetic", "hanging", "mathematical", "inherit"]).optional(),
  allowReorder: z.enum(["no", "yes"]).optional(),
  alphabetic: z.unknown().optional(),
  amplitude: z.unknown().optional(),
  arabicForm: z.enum(["initial", "medial", "terminal", "isolated"]).optional(),
  ascent: z.unknown().optional(),
  attributeName: z.string().optional(),
  attributeType: z.string().optional(),
  autoReverse: z.unknown().optional(),
  azimuth: z.unknown().optional(),
  baseFrequency: z.unknown().optional(),
  baselineShift: z.unknown().optional(),
  baseProfile: z.unknown().optional(),
  bbox: z.unknown().optional(),
  begin: z.unknown().optional(),
  bias: z.unknown().optional(),
  by: z.unknown().optional(),
  calcMode: z.unknown().optional(),
  capHeight: z.unknown().optional(),
  clip: z.unknown().optional(),
  clipPath: z.string().optional(),
  clipPathUnits: z.unknown().optional(),
  clipRule: z.unknown().optional(),
  colorInterpolation: z.unknown().optional(),
  colorInterpolationFilters: z.enum(["auto", "sRGB", "linearRGB", "inherit"]).optional(),
  colorProfile: z.unknown().optional(),
  colorRendering: z.unknown().optional(),
  contentScriptType: z.unknown().optional(),
  contentStyleType: z.unknown().optional(),
  cursor: z.unknown().optional(),
  cx: z.unknown().optional(),
  cy: z.unknown().optional(),
  d: z.string().optional(),
  decelerate: z.unknown().optional(),
  descent: z.unknown().optional(),
  diffuseConstant: z.unknown().optional(),
  direction: z.unknown().optional(),
  display: z.unknown().optional(),
  divisor: z.unknown().optional(),
  dominantBaseline: z.enum(["auto", "use-script", "no-change", "reset-size", "ideographic", "alphabetic", "hanging", "mathematical", "central", "middle", "text-after-edge", "text-before-edge", "inherit"]).optional(),
  dur: z.unknown().optional(),
  dx: z.unknown().optional(),
  dy: z.unknown().optional(),
  edgeMode: z.unknown().optional(),
  elevation: z.unknown().optional(),
  enableBackground: z.unknown().optional(),
  end: z.unknown().optional(),
  exponent: z.unknown().optional(),
  externalResourcesRequired: z.unknown().optional(),
  fill: z.string().optional(),
  fillOpacity: z.unknown().optional(),
  fillRule: z.enum(["nonzero", "evenodd", "inherit"]).optional(),
  filter: z.string().optional(),
  filterRes: z.unknown().optional(),
  filterUnits: z.unknown().optional(),
  floodColor: z.unknown().optional(),
  floodOpacity: z.unknown().optional(),
  focusable: z.unknown().optional(),
  fontFamily: z.string().optional(),
  fontSize: z.unknown().optional(),
  fontSizeAdjust: z.unknown().optional(),
  fontStretch: z.unknown().optional(),
  fontStyle: z.unknown().optional(),
  fontVariant: z.unknown().optional(),
  fontWeight: z.unknown().optional(),
  format: z.unknown().optional(),
  fr: z.unknown().optional(),
  from: z.unknown().optional(),
  fx: z.unknown().optional(),
  fy: z.unknown().optional(),
  g1: z.unknown().optional(),
  g2: z.unknown().optional(),
  glyphName: z.unknown().optional(),
  glyphOrientationHorizontal: z.unknown().optional(),
  glyphOrientationVertical: z.unknown().optional(),
  glyphRef: z.unknown().optional(),
  gradientTransform: z.string().optional(),
  gradientUnits: z.string().optional(),
  hanging: z.unknown().optional(),
  horizAdvX: z.unknown().optional(),
  horizOriginX: z.unknown().optional(),
  href: z.string().optional(),
  ideographic: z.unknown().optional(),
  imageRendering: z.unknown().optional(),
  in2: z.unknown().optional(),
  in: z.string().optional(),
  intercept: z.unknown().optional(),
  k1: z.unknown().optional(),
  k2: z.unknown().optional(),
  k3: z.unknown().optional(),
  k4: z.unknown().optional(),
  k: z.unknown().optional(),
  kernelMatrix: z.unknown().optional(),
  kernelUnitLength: z.unknown().optional(),
  kerning: z.unknown().optional(),
  keyPoints: z.unknown().optional(),
  keySplines: z.unknown().optional(),
  keyTimes: z.unknown().optional(),
  lengthAdjust: z.unknown().optional(),
  letterSpacing: z.unknown().optional(),
  lightingColor: z.unknown().optional(),
  limitingConeAngle: z.unknown().optional(),
  local: z.unknown().optional(),
  markerEnd: z.string().optional(),
  markerHeight: z.unknown().optional(),
  markerMid: z.string().optional(),
  markerStart: z.string().optional(),
  markerUnits: z.unknown().optional(),
  markerWidth: z.unknown().optional(),
  mask: z.string().optional(),
  maskContentUnits: z.unknown().optional(),
  maskUnits: z.unknown().optional(),
  mathematical: z.unknown().optional(),
  mode: z.unknown().optional(),
  numOctaves: z.unknown().optional(),
  offset: z.unknown().optional(),
  opacity: z.unknown().optional(),
  operator: z.unknown().optional(),
  order: z.unknown().optional(),
  orient: z.unknown().optional(),
  orientation: z.unknown().optional(),
  origin: z.unknown().optional(),
  overflow: z.unknown().optional(),
  overlinePosition: z.unknown().optional(),
  overlineThickness: z.unknown().optional(),
  paintOrder: z.unknown().optional(),
  panose1: z.unknown().optional(),
  path: z.string().optional(),
  pathLength: z.unknown().optional(),
  patternContentUnits: z.string().optional(),
  patternTransform: z.unknown().optional(),
  patternUnits: z.string().optional(),
  pointerEvents: z.unknown().optional(),
  points: z.string().optional(),
  pointsAtX: z.unknown().optional(),
  pointsAtY: z.unknown().optional(),
  pointsAtZ: z.unknown().optional(),
  preserveAlpha: z.unknown().optional(),
  preserveAspectRatio: z.string().optional(),
  primitiveUnits: z.unknown().optional(),
  r: z.unknown().optional(),
  radius: z.unknown().optional(),
  refX: z.unknown().optional(),
  refY: z.unknown().optional(),
  renderingIntent: z.unknown().optional(),
  repeatCount: z.unknown().optional(),
  repeatDur: z.unknown().optional(),
  requiredExtensions: z.unknown().optional(),
  requiredFeatures: z.unknown().optional(),
  restart: z.unknown().optional(),
  result: z.string().optional(),
  rotate: z.unknown().optional(),
  rx: z.unknown().optional(),
  ry: z.unknown().optional(),
  scale: z.unknown().optional(),
  seed: z.unknown().optional(),
  shapeRendering: z.unknown().optional(),
  slope: z.unknown().optional(),
  spacing: z.unknown().optional(),
  specularConstant: z.unknown().optional(),
  specularExponent: z.unknown().optional(),
  speed: z.unknown().optional(),
  spreadMethod: z.string().optional(),
  startOffset: z.unknown().optional(),
  stdDeviation: z.unknown().optional(),
  stemh: z.unknown().optional(),
  stemv: z.unknown().optional(),
  stitchTiles: z.unknown().optional(),
  stopColor: z.string().optional(),
  stopOpacity: z.unknown().optional(),
  strikethroughPosition: z.unknown().optional(),
  strikethroughThickness: z.unknown().optional(),
  string: z.unknown().optional(),
  stroke: z.string().optional(),
  strokeDasharray: z.unknown().optional(),
  strokeDashoffset: z.unknown().optional(),
  strokeLinecap: z.enum(["butt", "round", "square", "inherit"]).optional(),
  strokeLinejoin: z.enum(["miter", "round", "bevel", "inherit"]).optional(),
  strokeMiterlimit: z.unknown().optional(),
  strokeOpacity: z.unknown().optional(),
  strokeWidth: z.unknown().optional(),
  surfaceScale: z.unknown().optional(),
  systemLanguage: z.unknown().optional(),
  tableValues: z.unknown().optional(),
  targetX: z.unknown().optional(),
  targetY: z.unknown().optional(),
  textAnchor: z.enum(["start", "middle", "end", "inherit"]).optional(),
  textDecoration: z.unknown().optional(),
  textLength: z.unknown().optional(),
  textRendering: z.unknown().optional(),
  to: z.unknown().optional(),
  transform: z.string().optional(),
  u1: z.unknown().optional(),
  u2: z.unknown().optional(),
  underlinePosition: z.unknown().optional(),
  underlineThickness: z.unknown().optional(),
  unicode: z.unknown().optional(),
  unicodeBidi: z.unknown().optional(),
  unicodeRange: z.unknown().optional(),
  unitsPerEm: z.unknown().optional(),
  vAlphabetic: z.unknown().optional(),
  values: z.string().optional(),
  vectorEffect: z.unknown().optional(),
  version: z.string().optional(),
  vertAdvY: z.unknown().optional(),
  vertOriginX: z.unknown().optional(),
  vertOriginY: z.unknown().optional(),
  vHanging: z.unknown().optional(),
  vIdeographic: z.unknown().optional(),
  viewBox: z.string().optional(),
  viewTarget: z.unknown().optional(),
  visibility: z.unknown().optional(),
  vMathematical: z.unknown().optional(),
  widths: z.unknown().optional(),
  wordSpacing: z.unknown().optional(),
  writingMode: z.unknown().optional(),
  x1: z.unknown().optional(),
  x2: z.unknown().optional(),
  x: z.unknown().optional(),
  xChannelSelector: z.string().optional(),
  xHeight: z.unknown().optional(),
  xlinkActuate: z.string().optional(),
  xlinkArcrole: z.string().optional(),
  xlinkHref: z.string().optional(),
  xlinkRole: z.string().optional(),
  xlinkShow: z.string().optional(),
  xlinkTitle: z.string().optional(),
  xlinkType: z.string().optional(),
  xmlBase: z.string().optional(),
  xmlLang: z.string().optional(),
  xmlns: z.string().optional(),
  xmlnsXlink: z.string().optional(),
  xmlSpace: z.string().optional(),
  y1: z.unknown().optional(),
  y2: z.unknown().optional(),
  y: z.unknown().optional(),
  yChannelSelector: z.string().optional(),
  z: z.unknown().optional(),
  zoomAndPan: z.string().optional(),
  variant: z.enum(["glyph", "full"]).optional(), // Logo variant - `glyph`: Cloud icon only - `full`: Cloud icon with "CLOUDFLARE" wordmark below
});

export const CodePropsSchema = z.object({
  lang: z.enum(["ts", "tsx", "jsonc", "bash", "css"]).optional(), // Language hint for the code content. - `"ts"` — TypeScript code - `"tsx"` — TypeScript JSX code - `"jsonc"` — JSON with comments - `"bash"` — Shell/Bash commands - `"css"` — CSS styles
  code: z.string(), // The code string to display.
  values: z.unknown().optional(), // Template values for `{{key}}` interpolation. Values with `highlight: true` are visually emphasized.
  className: z.string().optional(), // Additional CSS classes merged via `cn()`.
});

export const CollapsiblePropsSchema = z.object({
  className: z.string().optional(), // Additional CSS classes
  onOpenChange: z.unknown().optional(), // Callback when collapsed state changes
});

export const ComboboxPropsSchema = z.object({
  size: z.enum(["xs", "sm", "base", "lg"]).optional(), // Size of the combobox trigger. Matches Input component sizes. - `"xs"` — Extra small for compact UIs (h-5 / 20px) - `"sm"` — Small for secondary fields (h-6.5 / 26px) - `"base"` — Default size (h-9 / 36px) - `"lg"` — Large for prominent fields (h-10 / 40px)
  inputSide: z.enum(["right", "top"]).optional(), // Position of the text input relative to chips in multi-select mode. - `"right"` — Input inline to the right of chips - `"top"` — Input above chips
  items: z.array(z.unknown()), // Array of items to display in the dropdown
  value: z.array(z.unknown()).optional(), // Currently selected value(s)
  children: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // Combobox content (trigger, content, items)
  className: z.string().optional(), // Additional CSS classes
  label: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // Label content for the combobox (enables Field wrapper) - can be a string or any React node
  required: z.boolean().optional(), // Whether the combobox is required
  labelTooltip: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // Tooltip content to display next to the label via an info icon
  description: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // Helper text displayed below the combobox
  error: z.unknown().optional(), // Error message or validation error object
  onValueChange: z.unknown().optional(), // Callback when selection changes
  multiple: z.boolean().optional(), // Allow multiple selections
  isItemEqualToValue: z.unknown().optional(), // Custom equality function for comparing items
});

export const CommandPalettePropsSchema = z.object({
  open: z.boolean(), // Whether the dialog is open
  children: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // Child content - typically one or more Panel components
  container: z.unknown().optional(), // Container element for the portal. Use this to render the command palette inside a Shadow DOM or custom container. Overrides `DevilPortalProvider` context.
});

export const DatePickerPropsSchema = z.object({
  className: z.string().optional(), // Additional CSS classes
  children: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // Child elements
});

export const DateRangePickerPropsSchema = z.object({
  size: z.enum(["sm", "base", "lg"]).optional(), // Calendar size. - `"sm"` — Compact calendar for tight spaces - `"base"` — Default calendar size - `"lg"` — Large calendar for prominent date selection
  variant: z.enum(["default", "subtle"]).optional(), // Visual variant. - `"default"` — Standard appearance with overlay background - `"subtle"` — Minimal background
  timezone: z.string().optional(), // Display timezone string shown in the footer.
  className: z.string().optional(), // Additional CSS classes merged via `cn()`.
  onStartDateChange: z.unknown().optional(), // Callback when start date changes
  onEndDateChange: z.unknown().optional(), // Callback when end date changes
});

export const DialogPropsSchema = z.object({
  className: z.string().optional(), // Additional CSS classes merged via `cn()`.
  children: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // Dialog content (typically Title, Description, Close, and action buttons).
  container: z.unknown().optional(), // Container element for the portal. Use this to render the dialog inside a Shadow DOM or custom container. Overrides `DevilPortalProvider` context.
  size: z.enum(["base", "sm", "lg", "xl"]).optional(), // Dialog width. - `"sm"` — Small (288px) for simple confirmations - `"base"` — Default (384px) - `"lg"` — Large (512px) for complex content - `"xl"` — Extra large (768px) for detailed views
});

export const DropdownMenuPropsSchema = z.object({
  variant: z.enum(["default", "danger"]).optional(), // Visual style of the dropdown item. - `"default"` — Standard item appearance - `"danger"` — Destructive action with red text
});

export const EmptyPropsSchema = z.object({
  size: z.enum(["sm", "base", "lg"]).optional(), // Size of the empty state container. - `"sm"` — Compact empty state for smaller containers - `"base"` — Default empty state size - `"lg"` — Large empty state for prominent placement
  icon: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // Decorative icon displayed above the title (e.g. from `@phosphor-icons/react`).
  title: z.string(), // Primary heading text for the empty state.
  description: z.string().optional(), // Secondary description text displayed below the title.
  commandLine: z.string().optional(), // Shell command displayed in a copyable code block.
  contents: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // Additional content (buttons, links) rendered below the description.
  className: z.string().optional(), // Additional CSS classes merged via `cn()`.
});

export const FieldPropsSchema = z.object({
  controlFirst: z.boolean().optional(), // When `true`, places the control before the label (for checkbox/switch layouts).
  children: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // The form control element(s) to wrap (Input, Select, Checkbox, etc.).
  label: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // The label content — can be a string or any React node.
  required: z.boolean().optional(), // When explicitly `false`, shows gray "(optional)" text after the label. When `true` or `undefined`, no indicator is shown.
  labelTooltip: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // Tooltip content displayed next to the label via an info icon.
  error: z.unknown().optional(), // Validation error with a message and a browser `ValidityState` match key.
  description: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // Helper text displayed below the control (hidden when `error` is present).
  hideLabel: z.boolean().optional(), // When `true`, Field renders layout, description, and error but skips the `<label>` element. Use when the child component provides its own accessible label (e.g. Select uses Base UI's `Select.Label` to avoid hover/focus coupling from native `<label>`).
});

export const GlobeMapPropsSchema = z.object({
  landColor: z.string().optional(), // Stroke color for the hatched land. Defaults to the neutral Devil map area color.
  landHatchSpacing: z.number().optional(), // Spacing between land hatch lines in view-box pixels. Default: `10`.
  oceanColor: z.string().optional(), // Fill behind the land and graticule. Default: the Devil base surface.
  markers: z.array(z.unknown()).optional(), // Geographic points drawn above the land. Points fade at the horizon and back-facing points are hidden.
  markerColor: z.string().optional(), // Default marker fill. Defaults to the Devil chart blue.
  markerRadius: z.number().optional(), // Default marker radius in view-box pixels. Default: `7`.
  defaultRotation: z.array(z.unknown()).optional(), // Initial globe rotation as `[longitude, latitude, roll]`.
  autoRotate: z.boolean().optional(), // Continuously rotate the globe horizontally. Default: `false`.
  autoRotateSpeed: z.number().optional(), // Horizontal auto-rotation speed in degrees per second. Default: `4`.
  showGraticule: z.boolean().optional(), // Draw latitude and longitude guides. Default: `false`.
  showTooltip: z.boolean().optional(), // Show the Devil-styled marker tooltip. Default: `true`.
  height: z.number().optional(), // Fixed component height. Otherwise the globe uses a square aspect ratio.
  className: z.string().optional(),
  isDarkMode: z.boolean().optional(),
});

export const GridPropsSchema = z.object({
  children: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // Grid items to render.
  className: z.string().optional(), // Additional CSS classes merged via `cn()`.
  id: z.string().optional(),
  lang: z.string().optional(),
  title: z.string().optional(),
  mobileDivider: z.boolean().optional(), // Show dividers between grid items on mobile (only works with `"4up"` variant).
  gap: z.enum(["none", "sm", "base", "lg"]).optional(), // Gap size between grid items. - `"none"` — No gap - `"sm"` — 12px gap - `"base"` — Responsive gap (8px → 24px → 32px) - `"lg"` — 32px gap
  variant: z.enum(["2up", "side-by-side", "2-1", "1-2", "1-3up", "3up", "4up", "6up", "1-2-4up"]).optional(), // Responsive column layout variant. - `"2up"` — 1 col → 2 cols at md - `"side-by-side"` — Always 2 cols - `"2-1"` — 66%/33% split at md - `"1-2"` — 33%/66% split at md - `"3up"` — 1 → 2 → 3 cols - `"4up"` — 1 → 2 → 3 → 4 cols - `"6up"` — 2 → 3 → 4 → 6 cols - `"1-2-4up"` — 1 → 2 → 4 cols
});

export const InputPropsSchema = z.object({
  label: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // Label content for the input (enables Field wrapper) - can be a string or any React node
  labelTooltip: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // Tooltip content to display next to the label via an info icon
  description: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // Helper text displayed below the input
  error: z.unknown().optional(), // Error message or validation error object
  passwordManagerIgnore: z.boolean().optional(), // Suppress browser extension password manager overlays on non-credential inputs.
  size: z.enum(["xs", "sm", "base", "lg"]).optional(), // Input size. - `"xs"` — Extra small for compact UIs - `"sm"` — Small for secondary fields - `"base"` — Default size - `"lg"` — Large for prominent fields
  variant: z.enum(["default", "error"]).optional(), // Visual variant. - `"default"` — Standard input - `"error"` — Error state for validation failures
});

export const InputAreaPropsSchema = z.object({
  size: z.enum(["xs", "sm", "base", "lg"]).optional(), // Input size. - `"xs"` — Extra small for compact UIs - `"sm"` — Small for secondary fields - `"base"` — Default size - `"lg"` — Large for prominent fields
  variant: z.enum(["default", "error"]).optional(), // Visual variant of the textarea.
  label: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // Label content for the textarea (enables Field wrapper) — can be a string or any React node.
  labelTooltip: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // Tooltip content to display next to the label via an info icon.
  description: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // Helper text displayed below the textarea.
  error: z.unknown().optional(), // Error message or validation error object.
  autoResize: z.boolean().optional(), // Automatically resize the textarea based on its content.
  minRows: z.number().optional(), // Minimum number of rows to display when `autoResize` is enabled.
  maxRows: z.number().optional(), // Maximum number of rows to grow to when `autoResize` is enabled; content beyond this scrolls.
  onValueChange: z.unknown().optional(), // Callback fired with the new string value on every change.
});

export const InputGroupPropsSchema = z.object({
  label: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // The label content — can be a string or any React node.
  description: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // Helper text displayed below the control (hidden when `error` is present).
  error: z.unknown().optional(), // Validation error with a message and a browser `ValidityState` match key.
  required: z.boolean().optional(), // When explicitly `false`, shows gray "(optional)" text after the label. When `true` or `undefined`, no indicator is shown.
  labelTooltip: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // Tooltip content displayed next to the label via an info icon.
  children: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(),
  className: z.string().optional(),
  id: z.string().optional(),
  lang: z.string().optional(),
  title: z.string().optional(),
  size: z.enum(["xs", "sm", "base", "lg"]).optional(),
  disabled: z.boolean().optional(),
});

export const LabelPropsSchema = z.object({
  children: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // The label content — can be a string or any React node.
  showOptional: z.boolean().optional(), // When `true`, shows gray "(optional)" text after the label.
  tooltip: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // Tooltip content displayed next to the label via an info icon.
  className: z.string().optional(), // Additional CSS classes merged via `cn()`.
  htmlFor: z.string().optional(), // The id of the form element this label is associated with
  asContent: z.boolean().optional(), // When true, only renders the inline content (indicators, tooltip) without the outer label element with font styling. Useful when composed inside another label element that already provides the text styling.
});

export const LayerCardPropsSchema = z.object({
  render: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // Allows you to replace the component's HTML element with a different tag, or compose it with another component. Accepts a `ReactElement` or a function that returns the element to render.
  children: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(),
  className: z.string().optional(),
  id: z.string().optional(),
  lang: z.string().optional(),
  title: z.string().optional(),
});

export const LayerDialogPropsSchema = z.object({
  dismissDisabled: z.boolean().optional(), // Prevent every user-initiated dismissal while dialog work is pending.
});

export const LinkPropsSchema = z.object({
  variant: z.enum(["inline", "current", "plain"]).optional(), // Visual style of the link. - `"inline"` — Inline text link that flows with content - `"current"` — Link that inherits color from parent text - `"plain"` — Link without underline decoration
  to: z.string().optional(),
  children: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(),
  className: z.string().optional(),
  id: z.string().optional(),
  lang: z.string().optional(),
  title: z.string().optional(),
  download: z.unknown().optional(),
  href: z.string().optional(),
  hrefLang: z.string().optional(),
  media: z.string().optional(),
  ping: z.string().optional(),
  target: z.unknown().optional(),
  type: z.string().optional(),
  referrerPolicy: z.enum(["", "no-referrer", "no-referrer-when-downgrade", "origin", "origin-when-cross-origin", "same-origin", "strict-origin", "strict-origin-when-cross-origin", "unsafe-url"]).optional(),
  render: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // Allows you to replace the component's HTML element with a different tag, or compose it with another component. Accepts a `ReactElement` or a function that returns the element to render.
});

export const LoaderPropsSchema = z.object({
  className: z.string().optional(), // Additional CSS classes merged via `cn()`.
  size: z.enum(["sm", "base", "lg"]).optional(), // Size of the spinner. Use a preset name or a custom pixel number. - `"sm"` — 16px, for inline use - `"base"` — 24px, default size - `"lg"` — 32px, for prominent loading states
});

export const MenuBarPropsSchema = z.object({
  className: z.string().optional(), // Additional CSS classes merged via `cn()`.
  isActive: z.unknown().optional(), // The currently active option value — matched against option index or `id`.
  options: z.array(z.unknown()), // Array of menu option configurations.
  optionIds: z.boolean().optional(), // When true, each option's `id` field is used for matching instead of its array index.
});

export const MeterPropsSchema = z.object({
  customValue: z.string().optional(), // Custom formatted value text (e.g. "750 / 1,000") displayed instead of percentage.
  label: z.string(), // Label text displayed above the meter track.
  showValue: z.boolean().optional(), // Whether to display the percentage value next to the label.
  trackClassName: z.string().optional(), // Additional CSS classes for the track (background bar).
  indicatorClassName: z.string().optional(), // Additional CSS classes for the indicator (filled bar).
  value: z.number().optional(), // Current value of the meter
  max: z.number().optional(), // Maximum value of the meter (default: 100)
  min: z.number().optional(), // Minimum value of the meter (default: 0)
});

export const PaginationPropsSchema = z.object({
  setPage: z.unknown(), // Callback when page changes
  page: z.number().optional(), // Current page number (1-indexed).
  perPage: z.number().optional(), // Number of items displayed per page.
  totalCount: z.number().optional(), // Total number of items across all pages.
  hasNextPage: z.boolean().optional(), // Whether another page exists when the total count is unknown. Ignored when `totalCount` is provided. Unknown totals use sequential controls only.
  className: z.string().optional(), // Additional CSS classes for the container
  labels: z.unknown().optional(), // Labels for internationalization of aria-labels. All labels have English defaults. For visible text like "Showing X of Y", use render props on sub-components: - `Pagination.Info` children for the info text - `Pagination.PageSize` label prop for the "Per page:" text
  children: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // Compound component children for custom layouts. Use Pagination.Info, Pagination.PageSize, Pagination.Controls, and Pagination.Separator.
  controls: z.enum(["full", "simple"]).optional(),
  text: z.unknown().optional(),
});

export const PopoverPropsSchema = z.object({
  side: z.enum(["top", "bottom", "left", "right"]).optional(), // Which side of the trigger the popover appears on. - `"top"` — Above the trigger - `"bottom"` — Below the trigger - `"left"` — Left of the trigger - `"right"` — Right of the trigger
});

export const RadioPropsSchema = z.object({
  variant: z.enum(["default", "error"]).optional(),
  appearance: z.unknown().optional(), // Visual appearance applied to all Radio.Item children. - `"default"` — Standard inline radio items - `"card"` — Choice card with border, padding, and highlighted selection state Individual items can override this with their own `appearance` prop.
  legend: z.string().optional(), // Legend text for the group (required for accessibility). For more control over legend styling, omit this prop and use `<Radio.Legend>` as a child instead.
  children: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]), // Child Radio.Item components (and optionally a Radio.Legend)
  orientation: z.unknown().optional(), // Layout direction of the radio items
  error: z.string().optional(), // Error message for the group
  description: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // Helper text for the group
  value: z.unknown().optional(), // The controlled value of the selected radio item.
  disabled: z.boolean().optional(), // Whether all radios in the group are disabled
  controlPosition: z.unknown().optional(), // Position of radio control relative to label: "start" puts radio before label, "end" puts label before radio. Defaults to "start" for default appearance and "end" for card appearance.
  name: z.string().optional(), // Form submission name for the radio group
  className: z.string().optional(), // Additional CSS classes
  defaultValue: z.unknown().optional(), // The uncontrolled initial value of the selected radio item.
  onValueChange: z.unknown().optional(), // Callback fired when the selected value changes. The second argument carries native event details about the interaction.
});

export const SankeyChartPropsSchema = z.object({
  echarts: z.unknown(), // The ECharts core instance imported by the consumer. Passed in rather than imported directly so the consumer controls which ECharts modules are bundled (tree-shaking).
  nodes: z.array(z.unknown()), // Array of nodes in the Sankey diagram
  links: z.array(z.unknown()), // Array of links connecting nodes by index
  height: z.number().optional(), // Height of the chart in pixels
  showNodeValues: z.boolean().optional(), // Show node values above labels (default: true if any node has a value)
  nodeLabelLayout: z.unknown().optional(), // Layout for node labels when showNodeValues is true. - 'stacked': value on top, name below (default) - 'inline': "value name" on a single line (better for small nodes)
  formatValue: z.unknown().optional(), // Format function for node values (default: toLocaleString)
  tooltipFormatter: z.unknown().optional(), // Custom tooltip formatter. Return HTML string or empty string to hide tooltip.
  nodeWidth: z.number().optional(),
  nodePadding: z.number().optional(),
  showTooltip: z.boolean().optional(),
  defaultNodeColor: z.string().optional(),
  left: z.unknown().optional(), // Left padding of the Sankey layout within the chart container. Accepts a number (px) or percentage string. ECharts default: '5%'.
  right: z.unknown().optional(), // Right padding of the Sankey layout within the chart container. Accepts a number (px) or percentage string. ECharts default: '5%'.
  linkColor: z.unknown().optional(), // Link fill style: 'gradient' blends source to target colors, 'gray' uses flat gray
  linkOpacity: z.number().optional(),
  className: z.string().optional(),
  isDarkMode: z.boolean().optional(),
});

export const SelectPropsSchema = z.object({
  align: z.enum(["start", "center", "end"]).optional(), // How to align the popup relative to the specified side.
  alignItemWithTrigger: z.boolean().optional(), // Whether the positioner overlaps the trigger so the selected item's text is aligned with the trigger's value text. This only applies to mouse input and is automatically disabled if there is not enough space.
  alignOffset: z.unknown().optional(), // Additional offset along the alignment axis in pixels. Also accepts a function that returns the offset to read the dimensions of the anchor and positioner elements, along with its side and alignment. The function takes a `data` object parameter with the following properties: - `data.anchor`: the dimensions of the anchor element with properties `width` and `height`. - `data.positioner`: the dimensions of the positioner element with properties `width` and `height`. - `data.side`: which side of the anchor element the positioner is aligned against. - `data.align`: how the positioner is aligned relative to the specified side.
  anchor: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // An element to position the popup against. By default, the popup will be positioned against the trigger.
  arrowPadding: z.number().optional(), // Minimum distance to maintain between the arrow and the edges of the popup. Use it to prevent the arrow element from hanging out of the rounded corners of a popup.
  collisionAvoidance: z.unknown().optional(), // Determines how to handle collisions when positioning the popup. `side` controls overflow on the preferred placement axis (`top`/`bottom` or `left`/`right`): - `'flip'`: keep the requested side when it fits; otherwise try the opposite side   (`top` and `bottom`, or `left` and `right`). - `'shift'`: never change side; keep the requested side and move the popup within   the clipping boundary so it stays visible. - `'none'`: do not correct side-axis overflow. `align` controls overflow on the alignment axis (`start`/`center`/`end`): - `'flip'`: keep side, but swap `start` and `end` when the requested alignment overflows. - `'shift'`: keep side and requested alignment, then nudge the popup along the   alignment axis to fit. - `'none'`: do not correct alignment-axis overflow. `fallbackAxisSide` controls fallback behavior on the perpendicular axis when the preferred axis cannot fit: - `'start'`: allow perpendicular fallback and try the logical start side first   (`top` before `bottom`, or `left` before `right` in LTR). - `'end'`: allow perpendicular fallback and try the logical end side first   (`bottom` before `top`, or `right` before `left` in LTR). - `'none'`: do not fallback to the perpendicular axis. When `side` is `'shift'`, explicitly setting `align` only supports `'shift'` or `'none'`. If `align` is omitted, it defaults to `'flip'`.
  collisionBoundary: z.unknown().optional(), // An element or a rectangle that delimits the area that the popup is confined to.
  collisionPadding: z.unknown().optional(), // Additional space to maintain from the edge of the collision boundary.
  disableAnchorTracking: z.boolean().optional(), // Whether to disable the popup from tracking any layout shift of its positioning anchor.
  positionMethod: z.enum(["absolute", "fixed"]).optional(), // Determines which CSS `position` property to use.
  side: z.enum(["top", "bottom", "left", "right", "inline-end", "inline-start"]).optional(), // Which side of the anchor element to align the popup against. May automatically change to avoid collisions.
  sideOffset: z.unknown().optional(), // Distance between the anchor and the popup in pixels. Also accepts a function that returns the distance to read the dimensions of the anchor and positioner elements, along with its side and alignment. The function takes a `data` object parameter with the following properties: - `data.anchor`: the dimensions of the anchor element with properties `width` and `height`. - `data.positioner`: the dimensions of the positioner element with properties `width` and `height`. - `data.side`: which side of the anchor element the positioner is aligned against. - `data.align`: how the positioner is aligned relative to the specified side.
  sticky: z.boolean().optional(), // Whether to maintain the popup in the viewport after the anchor element was scrolled out of view.
  className: z.string().optional(), // Additional CSS classes merged via `cn()`.
  render: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // Replaces the trigger element while preserving Select behavior.
  size: z.enum(["xs", "sm", "base", "lg"]).optional(), // Size of the select trigger. Matches Input component sizes.
  label: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // Label content for the select. When provided, enables the Field wrapper with a visible label above the select. For accessibility without a visible label, use `aria-label` instead.
  hideLabel: z.boolean().optional(),
  placeholder: z.string().optional(), // Placeholder text shown when no value is selected.
  loading: z.boolean().optional(), // When `true`, shows a skeleton loader in place of the selected value.
  disabled: z.boolean().optional(), // Whether the select is disabled.
  required: z.boolean().optional(), // Whether the select is required. When `false`, shows "(optional)" text.
  labelTooltip: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // Tooltip content displayed next to the label via an info icon.
  value: z.unknown().optional(), // Currently selected value (controlled mode).
  children: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // `Select.Option` elements to render in the dropdown.
  description: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // Helper text displayed below the select.
  error: z.unknown().optional(), // Error message string or validation error object with `match` key.
  onValueChange: z.unknown().optional(), // Callback when selection changes
  defaultValue: z.unknown().optional(), // Initial value for uncontrolled mode
  renderValue: z.unknown().optional(), // A function that returns a ReactNode to format the selected value in the trigger. Required when using object values. Use `placeholder` for the empty state.
  items: z.unknown().optional(), // Data structure of items rendered in the popup. Accepts a plain object map (`{ key: "Label" }`) or an array of `{ label, value }` for object/complex values.
  isItemEqualToValue: z.unknown().optional(), // Custom equality function for comparing items. Required when value is an object, since object identity (`===`) won't match across renders.
});

export const SensitiveInputPropsSchema = z.object({
  alt: z.string().optional(),
  autoComplete: z.unknown().optional(),
  checked: z.boolean().optional(),
  disabled: z.boolean().optional(),
  height: z.unknown().optional(),
  list: z.string().optional(),
  name: z.string().optional(),
  placeholder: z.string().optional(),
  readOnly: z.boolean().optional(),
  required: z.boolean().optional(),
  width: z.unknown().optional(),
  className: z.string().optional(),
  id: z.string().optional(),
  lang: z.string().optional(),
  title: z.string().optional(),
  children: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(),
  value: z.string().optional(), // Controlled value
  size: z.enum(["xs", "sm", "base", "lg"]).optional(), // Size of the input. - `"xs"` — Extra small for compact UIs - `"sm"` — Small for secondary fields - `"base"` — Default input size - `"lg"` — Large for prominent fields
  variant: z.enum(["default", "error"]).optional(), // Style variant of the input. - `"default"` — Default input appearance - `"error"` — Error state for validation failures
  label: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // Label content for the input (enables Field wrapper and sets masked state label) - can be a string or any React node
  labelTooltip: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // Tooltip content to display next to the label via an info icon
  description: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // Helper text displayed below the input
  error: z.unknown().optional(), // Error message or validation error object
});

export const SidebarPropsSchema = z.object({
  defaultOpen: z.boolean().optional(), // Initial open state when uncontrolled.
  open: z.boolean().optional(), // Controlled open state.
  variant: z.enum(["sidebar", "floating", "inset"]).optional(), // Sidebar layout variant.
  side: z.enum(["left", "right"]).optional(), // Which side the sidebar is on.
  collapsible: z.enum(["icon", "offcanvas", "none"]).optional(),
  resizable: z.boolean().optional(), // Enable drag-to-resize on the sidebar edge.
  defaultWidth: z.number().optional(), // Initial width in pixels when resizable.
  minWidth: z.number().optional(), // Minimum width in pixels when resizing.
  maxWidth: z.number().optional(), // Maximum width in pixels when resizing.
  contained: z.boolean().optional(), // When true, the collapsed sidebar uses absolute positioning instead of fixed, keeping it scoped inside a bounded parent. Useful for demos and embedded sidebars.
  peekable: z.boolean().optional(), // When true, hovering or focusing the collapsed sidebar temporarily expands it. The `state` will be `"peeking"` during the peek. Moving away collapses it back.
  animationDuration: z.number().optional(), // Duration of sidebar expand/collapse animation in milliseconds.
  mobileBreakpoint: z.number().optional(), // Viewport width (in px) below which the sidebar renders as a mobile dialog sheet instead of the desktop aside rail.
  children: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // Content — typically `<Sidebar>` + main content.
  className: z.string().optional(), // Additional CSS classes for the wrapper div.
});

export const SurfacePropsSchema = z.object({
  as: z.unknown().optional(),
  render: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // Allows you to replace the component's HTML element with a different tag, or compose it with another component. Accepts a `ReactElement` or a function that returns the element to render.
  children: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(),
  className: z.string().optional(),
  id: z.string().optional(),
  lang: z.string().optional(),
  title: z.string().optional(),
});

export const SwitchPropsSchema = z.object({
  variant: z.enum(["default", "neutral"]).optional(), // Visual variant: "default" (pill, brand color) or "neutral" (squircle, monochrome)
  label: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // Label content for the switch (Field wrapper is built-in) - can be a string or any React node. Optional when used standalone for visual-only purposes.
  labelTooltip: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // Tooltip content to display next to the label via an info icon
  required: z.boolean().optional(), // Whether the switch is required. When explicitly false, shows "(optional)" text after the label.
  controlFirst: z.boolean().optional(), // When true (default), switch appears before label. When false, label appears before switch.
  size: z.enum(["sm", "base", "lg"]).optional(),
  checked: z.boolean().optional(),
  disabled: z.boolean().optional(),
  transitioning: z.boolean().optional(),
  name: z.string().optional(),
  type: z.enum(["submit", "reset", "button"]).optional(),
  value: z.unknown().optional(),
  className: z.string().optional(),
  id: z.string().optional(),
  lang: z.string().optional(),
  title: z.string().optional(),
  onClick: z.unknown(), // Callback when switch is clicked
});

export const TablePropsSchema = z.object({
  layout: z.enum(["auto", "fixed"]).optional(),
  variant: z.enum(["default", "selected"]).optional(),
  sticky: z.enum(["left", "right"]).optional(),
  className: z.string().optional(), // Additional CSS classes
  children: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // Child elements
});

export const TableOfContentsPropsSchema = z.object({
  children: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(),
  className: z.string().optional(),
  id: z.string().optional(),
  lang: z.string().optional(),
  title: z.string().optional(),
});

export const TabsPropsSchema = z.object({
  tabs: z.array(z.unknown()).optional(), // Array of tab items to render.
  value: z.string().optional(), // Controlled value. When set, component becomes controlled.
  selectedValue: z.string().optional(), // Default selected value for uncontrolled mode. Ignored when `value` is set.
  activateOnFocus: z.boolean().optional(), // When `true`, tabs are activated immediately upon receiving focus via arrow keys. When `false` (default), tabs receive focus but require Enter/Space to activate.
  className: z.string().optional(), // Additional CSS classes for the root element.
  listClassName: z.string().optional(), // Additional CSS classes for the tab list element.
  indicatorClassName: z.string().optional(), // Additional CSS classes for the indicator element.
  labels: z.unknown().optional(), // Labels for internationalization of aria-labels. All labels have English defaults.
  variant: z.enum(["segmented", "underline"]).optional(), // Tab style. - `"segmented"` — Pill-shaped indicator on a filled track - `"underline"` — Underline indicator below tab text
  size: z.enum(["base", "sm"]).optional(), // Tab size. - `"base"` — Default size (h-9, text-base) - `"sm"` — Compact size (h-6.5, text-xs) — matches Input size="sm"
  onValueChange: z.unknown().optional(), // Callback when active tab changes
});

export const TagInputPropsSchema = z.object({
  alt: z.string().optional(),
  autoComplete: z.unknown().optional(),
  checked: z.boolean().optional(),
  height: z.unknown().optional(),
  list: z.string().optional(),
  name: z.string().optional(),
  placeholder: z.string().optional(),
  readOnly: z.boolean().optional(),
  required: z.boolean().optional(),
  type: z.unknown().optional(),
  width: z.unknown().optional(),
  className: z.string().optional(),
  id: z.string().optional(),
  lang: z.string().optional(),
  title: z.string().optional(),
  children: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(),
  value: z.array(z.string()).optional(),
  validateValue: z.unknown().optional(),
  maxValues: z.number().optional(),
  labels: z.unknown().optional(), // Translated labels for generated input, action, and validation text.
  label: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(),
  labelTooltip: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(),
  description: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(),
  error: z.unknown().optional(),
  variant: z.enum(["default", "error"]).optional(),
  disabled: z.boolean().optional(),
});

export const TextPropsSchema = z.object({
  variant: z.enum(["heading", "heading1", "heading2", "heading3", "body", "secondary", "success", "error", "mono", "mono-secondary"]).optional(), // Text style variant. Determines color, font, and weight. - `"heading"` — Heading text (16px by default, 20px with `size="lg"`; semibold) - `"heading1"` — Deprecated; use `"heading"` (30px, semibold) - `"heading2"` — Deprecated; use `"heading"` (24px, semibold) - `"heading3"` — Deprecated; use `"heading"` (16px, semibold) - `"body"` — Default body text - `"secondary"` — Muted text for secondary information - `"success"` — Success state text - `"error"` — Error state text - `"mono"` — Monospace text for code - `"mono-secondary"` — Muted monospace text
  size: z.enum(["xs", "sm", "base", "lg"]).optional(), // Text size. Supported values depend on the variant: - `"heading"` — 16px when omitted, or 20px with `"lg"` - Body variants — `"xs"` (12px), `"sm"` (13px), `"base"` (14px),   or `"lg"` (16px) - Monospace variants — 13px when omitted, or 14px with `"lg"`
  bold: z.boolean().optional(), // Whether to use bold font weight (only applies to body variants).
  truncate: z.boolean().optional(), // Whether to truncate overflowing text with an ellipsis. Adds `truncate min-w-0` classes.
  as: z.enum(["h1", "h2", "h3", "h4", "h5", "h6", "p", "span", "label", "dt", "dd", "li", "figcaption", "legend", "pre", "code", "em", "strong", "small", "abbr", "time"]).optional(), // The HTML element to render. Accepts headings (`"h1"`–`"h6"`), block text (`"p"`, `"pre"`), inline text (`"span"`, `"code"`, `"em"`, `"strong"`, `"small"`, `"abbr"`, `"time"`), form-related (`"label"`, `"legend"`), list/definition (`"dt"`, `"dd"`, `"li"`), and `"figcaption"`. - **Optional** for `"heading"` (defaults to `"span"`). Pass the heading   element that reflects this text's place in the document outline. - **Required** for deprecated heading variants (`"heading1"`,   `"heading2"`, `"heading3"`). - **Optional** for body variants (defaults to `"p"`) and monospace   variants (defaults to `"span"`).
  children: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // Text content.
});

export const TimeseriesChartPropsSchema = z.object({
  echarts: z.unknown(), // The ECharts core instance imported by the consumer. Passed in rather than imported directly so the consumer controls which ECharts modules are bundled (tree-shaking).
  type: z.unknown().optional(), // Visual style of each series. Defaults to `"line"`.
  data: z.array(z.unknown()), // Array of time series data to display on the chart
  markers: z.array(z.unknown()).optional(), // Vertical reference markers rendered on the time axis.
  thresholds: z.array(z.unknown()).optional(), // Horizontal threshold lines rendered on the value axis.
  xAxisName: z.string().optional(), // Label for the x-axis (time axis)
  xAxisTickCount: z.number().optional(), // Number of ticks to display on the x-axis
  xAxisTickFormat: z.unknown().optional(), // Custom formatter for x-axis tick labels. Receives the raw timestamp in milliseconds and returns a display string, overriding ECharts' built-in time formatting.
  yAxisTickFormat: z.unknown().optional(), // Custom formatter for y-axis tick labels. Receives the raw value and returns a display string. When omitted, ECharts' built-in formatter is used.
  yAxisTickLabelFormat: z.unknown().optional(),
  yAxisName: z.string().optional(), // Label for the y-axis (value axis)
  yAxisTickCount: z.number().optional(), // Number of ticks to display on the y-axis
  yAxisMinInterval: z.number().optional(), // Minimum interval between y-axis ticks. Set to `1` for discrete count data so ECharts does not render fractional tick marks.
  tooltipValueFormat: z.unknown().optional(), // Custom formatter for tooltip values. Receives the raw y-value and returns a display string. When omitted, the raw value is shown. Takes precedence over the deprecated `yAxisTickLabelFormat` prop.
  tooltipFooter: z.string().optional(), // Footer text rendered below the series rows in the tooltip. Intended for brief context such as data freshness or aggregation details. Available for every `TimeseriesChart` configuration.
  tooltipMode: z.unknown().optional(), // Controls which series are shown in the tooltip. - `"all"` — show all series at the hovered timestamp (default) - `"single"` — show only the series whose value is closest to the cursor
  tooltipMaxItems: z.number().optional(), // Maximum number of series rows shown in the tooltip when `tooltipMode` is `"all"`. Additional series are hidden with a `+N more` footer. Defaults to `10`.
  tooltipBoundary: z.array(z.unknown()).optional(), // Constrains the tooltip to stay within a specific element or region. By default the tooltip avoids overflowing any clipping ancestor (scroll containers, viewports, etc.). Pass an `Element` or array of elements to restrict the tooltip to a specific container.
  tooltipFollowCursor: z.unknown().optional(), // Which axis the tooltip follows the cursor on. - `"both"` — tooltip tracks the cursor on both axes, staying near the pointer at all times. This is the default and matches the behaviour of ECharts' built-in tooltip. - `"x"` — tooltip follows the cursor horizontally but is locked to a fixed vertical position relative to the chart. This keeps the tooltip out of the way of the data and avoids vertical jitter as series values change — the same approach used by Recharts and many dashboard UIs. Only these two modes are offered because the x-axis is always time in a `TimeseriesChart`: y-only tracking and fully-fixed positioning don't produce useful tooltip behaviour for time-series data. Powered by Base UI Tooltip's `trackCursorAxis` under the hood.
  incomplete: z.unknown().optional(), // Indicates incomplete data periods with optional before/after timestamps in ms
  enableLegendSelection: z.boolean().optional(), // When `true`, adds a hidden ECharts legend so consumers can drive series visibility imperatively via the `legendSelect` / `legendUnSelect` / `legendToggleSelect` actions (e.g. to build a custom interactive legend). Toggled-off series are also excluded from the tooltip. Requires the consumer to register ECharts' `LegendComponent` (`echarts.use([LegendComponent])`); otherwise the legend actions no-op and, in development, ECharts logs a "component legend is used but not imported" warning.
  height: z.number().optional(), // Height of the chart in pixels. Defaults to `350`.
  isDarkMode: z.boolean().optional(), // When `true`, switches the chart to ECharts' built-in dark theme
  gradient: z.boolean().optional(), // When `true`, renders a vertical gradient fill beneath each line series. The gradient fades from the series' color at the top to transparent at the bottom. Has no effect when `type` is `"bar"`.
  loading: z.boolean().optional(), // When `true`, hides the chart and displays a skeleton matching the chart type with a subtle shimmer.
  ariaDescription: z.string().optional(), // Accessible description for screen readers. When provided, it is passed to ECharts' `aria.label.description` and announced when the chart receives focus. Consumers are responsible for writing a meaningful description — see the W3C guidance on complex images for recommendations.
  optionUpdateBehavior: z.unknown().optional(), // Additional options passed as the second argument to `chart.setOption()`. Defaults to `{ notMerge: false, lazyUpdate: true }`.
});

export const ToastyPropsSchema = z.object({
  variant: z.enum(["default", "success", "error", "warning", "info"]).optional(),
  children: z.unknown(), // Application content. Toasts render via a portal above this.
  container: z.unknown().optional(), // Container element for the portal. Use this to render toasts inside a Shadow DOM or custom container. Overrides `DevilPortalProvider` context.
  toastManager: z.unknown().optional(), // Optional toast manager created by `createDevilToastManager()`. When provided, allows code outside the React tree (timers, module-load callbacks, query-cache listeners) to dispatch toasts via the same dedupe-aware manager that `useDevilToastManager()` returns inside the tree. Forwarded to the underlying `@base-ui/react/toast` `Toast.Provider` `toastManager` prop — see https://base-ui.com/react/components/toast for the upstream primitive.
});

export const ToolbarPropsSchema = z.object({
  disabled: z.boolean().optional(),
  orientation: z.unknown().optional(), // The orientation of the toolbar.
  loopFocus: z.boolean().optional(), // If `true`, using keyboard navigation will wrap focus to the other end of the toolbar once the end is reached.
  id: z.string().optional(),
  lang: z.string().optional(),
  title: z.string().optional(),
  className: z.unknown().optional(), // CSS class applied to the element, or a function that returns a class based on the component's state.
  render: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // Allows you to replace the component's HTML element with a different tag, or compose it with another component. Accepts a `ReactElement` or a function that returns the element to render.
  children: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // Toolbar controls rendered as one grouped card.
  size: z.enum(["xs", "sm", "base", "lg"]).optional(), // Locks every toolbar item to this size.
});

export const TooltipPropsSchema = z.object({
  side: z.enum(["top", "bottom", "left", "right"]).optional(),
  className: z.string().optional(), // Additional CSS classes
  children: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]).optional(), // Child elements
  content: z.union([z.string(), z.number(), z.boolean(), z.null(), DynamicValueSchema]), // Content to display in the tooltip
});

// =============================================================================
// Component Type Union
// =============================================================================

/**
 * All valid component type names
 */
export type DevilComponentType = "Autocomplete" | "Badge" | "Banner" | "Breadcrumbs" | "BubbleMap" | "Button" | "ButtonGroup" | "Chart" | "Checkbox" | "ChoroplethMap" | "ClipboardText" | "CloudflareLogo" | "Code" | "Collapsible" | "Combobox" | "CommandPalette" | "DatePicker" | "DateRangePicker" | "Dialog" | "DropdownMenu" | "Empty" | "Field" | "GlobeMap" | "Grid" | "Input" | "InputArea" | "InputGroup" | "Label" | "LayerCard" | "LayerDialog" | "Link" | "Loader" | "MenuBar" | "Meter" | "Pagination" | "Popover" | "Radio" | "SankeyChart" | "Select" | "SensitiveInput" | "Sidebar" | "Surface" | "Switch" | "Table" | "TableOfContents" | "Tabs" | "TagInput" | "Text" | "TimeseriesChart" | "Toasty" | "Toolbar" | "Tooltip";

export const DevilComponentTypeSchema = z.enum([
  "Autocomplete",
  "Badge",
  "Banner",
  "Breadcrumbs",
  "BubbleMap",
  "Button",
  "ButtonGroup",
  "Chart",
  "Checkbox",
  "ChoroplethMap",
  "ClipboardText",
  "CloudflareLogo",
  "Code",
  "Collapsible",
  "Combobox",
  "CommandPalette",
  "DatePicker",
  "DateRangePicker",
  "Dialog",
  "DropdownMenu",
  "Empty",
  "Field",
  "GlobeMap",
  "Grid",
  "Input",
  "InputArea",
  "InputGroup",
  "Label",
  "LayerCard",
  "LayerDialog",
  "Link",
  "Loader",
  "MenuBar",
  "Meter",
  "Pagination",
  "Popover",
  "Radio",
  "SankeyChart",
  "Select",
  "SensitiveInput",
  "Sidebar",
  "Surface",
  "Switch",
  "Table",
  "TableOfContents",
  "Tabs",
  "TagInput",
  "Text",
  "TimeseriesChart",
  "Toasty",
  "Toolbar",
  "Tooltip",
]);

/**
 * Map of component type to its props schema
 */
export const ComponentPropsSchemas = {
  Autocomplete: AutocompletePropsSchema,
  Badge: BadgePropsSchema,
  Banner: BannerPropsSchema,
  Breadcrumbs: BreadcrumbsPropsSchema,
  BubbleMap: BubbleMapPropsSchema,
  Button: ButtonPropsSchema,
  ButtonGroup: ButtonGroupPropsSchema,
  Chart: ChartPropsSchema,
  Checkbox: CheckboxPropsSchema,
  ChoroplethMap: ChoroplethMapPropsSchema,
  ClipboardText: ClipboardTextPropsSchema,
  CloudflareLogo: CloudflareLogoPropsSchema,
  Code: CodePropsSchema,
  Collapsible: CollapsiblePropsSchema,
  Combobox: ComboboxPropsSchema,
  CommandPalette: CommandPalettePropsSchema,
  DatePicker: DatePickerPropsSchema,
  DateRangePicker: DateRangePickerPropsSchema,
  Dialog: DialogPropsSchema,
  DropdownMenu: DropdownMenuPropsSchema,
  Empty: EmptyPropsSchema,
  Field: FieldPropsSchema,
  GlobeMap: GlobeMapPropsSchema,
  Grid: GridPropsSchema,
  Input: InputPropsSchema,
  InputArea: InputAreaPropsSchema,
  InputGroup: InputGroupPropsSchema,
  Label: LabelPropsSchema,
  LayerCard: LayerCardPropsSchema,
  LayerDialog: LayerDialogPropsSchema,
  Link: LinkPropsSchema,
  Loader: LoaderPropsSchema,
  MenuBar: MenuBarPropsSchema,
  Meter: MeterPropsSchema,
  Pagination: PaginationPropsSchema,
  Popover: PopoverPropsSchema,
  Radio: RadioPropsSchema,
  SankeyChart: SankeyChartPropsSchema,
  Select: SelectPropsSchema,
  SensitiveInput: SensitiveInputPropsSchema,
  Sidebar: SidebarPropsSchema,
  Surface: SurfacePropsSchema,
  Switch: SwitchPropsSchema,
  Table: TablePropsSchema,
  TableOfContents: TableOfContentsPropsSchema,
  Tabs: TabsPropsSchema,
  TagInput: TagInputPropsSchema,
  Text: TextPropsSchema,
  TimeseriesChart: TimeseriesChartPropsSchema,
  Toasty: ToastyPropsSchema,
  Toolbar: ToolbarPropsSchema,
  Tooltip: TooltipPropsSchema,
} as const;

// =============================================================================
// UI Element & Tree Schemas
// =============================================================================

/**
 * Base UI element structure
 */
export const UIElementBaseSchema = z.object({
  key: z.string(),
  type: DevilComponentTypeSchema,
  props: z.record(z.string(), z.unknown()),
  children: z.array(z.string()).optional(),
  parentKey: z.string().nullable().optional(),
  visible: VisibilityConditionSchema.optional(),
  action: ActionSchema.optional(),
});

export type UIElement = z.infer<typeof UIElementBaseSchema>;

/**
 * Flat UI tree structure (optimized for LLM generation)
 */
export const UITreeSchema = z.object({
  root: z.string(),
  elements: z.record(z.string(), UIElementBaseSchema),
});

export type UITree = z.infer<typeof UITreeSchema>;

// =============================================================================
// Validation Helpers
// =============================================================================

/**
 * Validate an element's props against its component schema
 */
export function validateElementProps(element: UIElement): SafeParseResult<unknown> {
  const schema = ComponentPropsSchemas[element.type as keyof typeof ComponentPropsSchemas];
  if (!schema) {
    return { success: false, error: new z.ZodError([{ code: 'custom', message: `Unknown component type: ${element.type}`, path: ['type'] }]) };
  }
  return schema.safeParse(element.props);
}

/**
 * Validate a complete UI tree
 */
export function validateUITree(tree: unknown): SafeParseResult<UITree> {
  return UITreeSchema.safeParse(tree);
}

/**
 * List of all component names (for catalog generation)
 */
export const DEVIL_COMPONENT_NAMES = ["Autocomplete", "Badge", "Banner", "Breadcrumbs", "BubbleMap", "Button", "ButtonGroup", "Chart", "Checkbox", "ChoroplethMap", "ClipboardText", "CloudflareLogo", "Code", "Collapsible", "Combobox", "CommandPalette", "DatePicker", "DateRangePicker", "Dialog", "DropdownMenu", "Empty", "Field", "GlobeMap", "Grid", "Input", "InputArea", "InputGroup", "Label", "LayerCard", "LayerDialog", "Link", "Loader", "MenuBar", "Meter", "Pagination", "Popover", "Radio", "SankeyChart", "Select", "SensitiveInput", "Sidebar", "Surface", "Switch", "Table", "TableOfContents", "Tabs", "TagInput", "Text", "TimeseriesChart", "Toasty", "Toolbar", "Tooltip"] as const;
