import { defineConfig } from "vite-plus";

// Fingerprint source/configuration, not pnpm's machine-specific install state
// or directory listings that change when generated outputs are absent in CI.
const toolchainInputs = [
  "package.json",
  "pnpm-lock.yaml",
  "pnpm-workspace.yaml",
  ".node-version",
  ".npmrc",
  "tsconfig.json",
  "vite.config.ts",
  "patches/**",
];
const demoInputs = [
  ...toolchainInputs,
  "packages/kumo-docs-astro/package.json",
  "packages/kumo-docs-astro/tsconfig.json",
  "packages/kumo-docs-astro/scripts/extract-demo-examples.ts",
  "packages/kumo-docs-astro/src/components/demos/**",
];
const registryInputs = [
  ...demoInputs,
  "packages/devil-ui/package.json",
  "packages/devil-ui/tsconfig.json",
  "packages/devil-ui/src/**",
  "packages/devil-ui/scripts/**",
];

export default defineConfig({
  staged: {
    "*": "vp check --fix",
  },
  run: {
    // We use pnpm until
    // https://github.com/voidzero-dev/vite-plus/issues/2238 is fixed.
    tasks: {
      "gen:demos": {
        command: "pnpm --filter @cloudflare/kumo-docs-astro codegen:demos",
        input: demoInputs,
        output: ["packages/kumo-docs-astro/dist/demo-metadata.json"],
      },
      "gen:registry": {
        command: "tsx packages/devil-ui/scripts/component-registry/index.ts",
        dependsOn: ["gen:demos"],
        input: registryInputs,
        // Restore the memo too: the package build invokes codegen a second time.
        output: [
          "packages/devil-ui/ai/**",
          "packages/devil-ui/.cache/component-registry-cache.json",
        ],
      },
      "build:devil": {
        command: "pnpm --filter @hellwrk/devil-ui build",
        // Pre-warms the registry memo so the in-build codegen pass is incremental.
        dependsOn: ["gen:registry"],
        input: [
          ...demoInputs,
          ".gitignore",
          "packages/devil-ui/**",
          "!packages/devil-ui/node_modules/**",
          "!packages/devil-ui/ai/**",
          "!packages/devil-ui/dist/**",
          "!packages/devil-ui/.cache/**",
          "!packages/devil-ui/**/*.tsbuildinfo",
        ],
      },
      "gen:figma-data": {
        command: "pnpm --filter @cloudflare/kumo-figma build:data",
      },
      "build:docs": {
        command: "pnpm --filter @cloudflare/kumo-docs-astro build",
        // The docs site consumes the built devil package.
        dependsOn: ["build:devil"],
        // The build regenerates these itself; outputs, not inputs.
        input: [
          { auto: true },
          "!packages/kumo-docs-astro/.astro/**",
          "!packages/kumo-docs-astro/public/skill.md",
          "!packages/kumo-docs-astro/dist/**",
        ],
      },
    },
  },
  fmt: {
    // Match the repo's previous Prettier print width.
    printWidth: 80,
    ignorePatterns: [
      // Mustache tag names in plop templates break Oxfmt's Handlebars parser.
      "**/*.hbs",
      // Generated by `wrangler types`.
      "packages/kumo-screenshot-worker/worker-configuration.d.ts",
      // TEMPORARY: MDX formatting changes rendered output (JSX-children
      // whitespace); native support tracked in https://github.com/oxc-project/oxc/issues/24608
      "**/*.mdx",
      // Oxfmt diffs from Prettier on long CSS lines: https://github.com/oxc-project/oxc/issues/24843
      "packages/devil-ui/src/styles/devil.css",
      // TEMPORARY: Oxfmt doesn't follow Prettier 3.9's union wrapping yet: https://github.com/oxc-project/oxc/issues/23923
      "packages/kumo-docs-astro/src/components/demos/Chart/ColorDemo.tsx",
      "packages/kumo-figma/src/generators/shared.ts",
      "packages/kumo-figma/src/parsers/tailwind-to-figma.ts",
      "packages/devil-ui/src/components/chart/Color.ts",
      "packages/devil-ui/src/components/dialog/dialog.tsx",
      "packages/devil-ui/src/components/toast/toast.tsx",
      "packages/devil-ui/src/utils/portal-provider.tsx",
      "packages/devil-ui/src/utils/resolve-variant.ts",
      "tools/deployments/validate-pr-description.ts",
    ],
    // Replaces prettier-plugin-tailwindcss; the stylesheet teaches devil-* utilities.
    sortTailwindcss: {
      functions: ["cn", "clsx"],
      stylesheet: "./packages/devil-ui/src/styles/devil-standalone.css",
    },
  },
  lint: {
    // ci/ and tools/ were never linted; figma scripts import devil's non-exported files.
    ignorePatterns: ["ci/**", "tools/**", "packages/kumo-figma/scripts/**"],
    jsPlugins: [
      "./packages/devil-ui/lint/devil-plugin.js",
      {
        name: "vite-plus",
        specifier: "vite-plus/oxlint-plugin",
      },
    ],
    plugins: ["eslint", "typescript"],
    categories: {
      correctness: "error",
    },
    rules: {
      "devil/no-cross-package-imports": "error",
      "devil/no-primitive-colors": "error",
      "devil/no-tailwind-dark-variant": "error",
      "devil/no-flow-node-custom-render": "error",
      "vite-plus/prefer-vite-plus-imports": "error",
    },
    options: {
      typeAware: true,
      typeCheck: true,
    },
  },
});
